server:
  port: 8888


spring:
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: proxy

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none #create, update
    defer-datasource-initialization: false
  sql:
    init:
      mode: never #always


jasypt:
  encryptor:
    password: encryptKeyTestKey